### PR TITLE
Mention FreeBSD package in README

### PR DESCRIPTION
**Pull request by 0mp**

### CODE REVIEW

**Comment by akinomyoga** [comment]
OK, thank you for the information! Hmm, @nunotexbsd are you the maintainer of the package `misc/cxxmatrix` in FreeBSD? Would you mind if we add your GitHub account name to the README as the maintainer of the FreeBSD package?

**Comment by akinomyoga** [comment]
It seems there's no reply from @nunotexbsd, so I'd merge this PR as is. @0mp Thank you for opening the PR!

**Comment by 0mp** [comment]
Cheers!

**Comment by nunotexbsd** [comment]
Hello!

Sorry I miss this pull request. 

Yes you can add my account name to README or my maintainer e-mail adress eduardo@FreeBSD.org as described in https://www.freshports.org/misc/cxxmatrix/

Thanks!
Nuno Teixeira

**Comment by akinomyoga** [comment]
@nunotexbsd Thank you for your reply! I have updated README.

**Pull request merged**
